spring:
  application:
    name: plishka-backend
    project_version: 1

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  config:
    import: optional:file:.env[.properties]

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_ACCESS_SECRET}
  expiration: ${JWT_ACCESS_EXPIRATION}

backend:
  base-url: ${BACKEND_BASE_URL}
  refresh-token-expiration: ${BACKEND_REFRESH_TOKEN_EXPIRATION}
  auth:
    email-verification-token-ttl: ${BACKEND_AUTH_EMAIL_VERIFICATION_TOKEN_TTL}
    password-reset-token-ttl: ${BACKEND_AUTH_PASSWORD_RESET_TOKEN_TTL}
  cleanup:
    unverified-user-ttl: ${BACKEND_CLEANUP_UNVERIFIED_USER_TTL}

frontend:
  reset-password-url: ${FRONTEND_RESET_PASSWORD_URL}
