package org.plishka.backend.dto.file;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import java.util.Map;
import lombok.Builder;
import org.plishka.backend.openapi.support.OpenApiExampleValues;

@Builder
@Schema(description = "Presigned upload URL response.")
public record PresignUploadResponseDto(
        @Schema(
                description = "Opaque S3 object key generated by the server.",
                example = OpenApiExampleValues.PRODUCT_IMAGE_S3_KEY
        )
        String s3Key,
        @Schema(description = "Temporary presigned upload URL.", example = OpenApiExampleValues.PRESIGNED_STORAGE_URL)
        String uploadUrl,
        @Schema(description = "HTTP method to use with the presigned URL.", example = "PUT")
        String method,
        @Schema(
                description = "URL expiration timestamp in UTC ISO-8601 format.",
                example = OpenApiExampleValues.PRESIGNED_URL_EXPIRES_AT
        )
        Instant expiresAt,
        @Schema(
                description = "Headers clients must send when uploading to the presigned URL.",
                example = OpenApiExampleValues.PRESIGN_UPLOAD_REQUIRED_HEADERS_JSON
        )
        Map<String, String> requiredHeaders
) {
}
