package org.plishka.backend.validation;

import jakarta.validation.Constraint;
import jakarta.validation.Payload;
import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import org.plishka.backend.validation.impl.RefreshTokenValidator;

/**
 * Validates a refresh token generated by the application.
 *
 * <p>Validation rules:
 * <ul>
 *   <li>{@code null}, an empty string, and a blank string are invalid.</li>
 *   <li>The value must be exactly {@code 86} characters long.</li>
 *   <li>Only URL-safe Base64 characters are allowed: Latin letters, digits, underscore, and
 *   hyphen.</li>
 *   <li>Padding characters and any other symbols are not allowed.</li>
 * </ul>
 */
@Target({ElementType.PARAMETER, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Constraint(validatedBy = RefreshTokenValidator.class)
public @interface ValidRefreshToken {
    String message() default "Refresh token has invalid format";

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};
}
