package org.plishka.backend.controller.auth;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.net.URI;
import lombok.RequiredArgsConstructor;
import org.plishka.backend.config.properties.FrontendProperties;
import org.plishka.backend.dto.auth.AuthResponseDto;
import org.plishka.backend.dto.auth.ForgotPasswordRequestDto;
import org.plishka.backend.dto.auth.LoginRequestDto;
import org.plishka.backend.dto.auth.RefreshTokenRequestDto;
import org.plishka.backend.dto.auth.RegisterRequestDto;
import org.plishka.backend.dto.auth.ResendVerificationEmailRequestDto;
import org.plishka.backend.dto.auth.ResetPasswordRequestDto;
import org.plishka.backend.dto.auth.VerifyEmailChangeRequestDto;
import org.plishka.backend.dto.common.MessageResponseDto;
import org.plishka.backend.openapi.support.OpenApiExampleValues;
import org.plishka.backend.security.AuthenticatedUserPrincipal;
import org.plishka.backend.service.auth.AuthService;
import org.plishka.backend.service.user.EmailChangeService;
import org.plishka.backend.validation.ValidDeviceId;
import org.plishka.backend.validation.ValidEmailActionToken;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/auth")
@RequiredArgsConstructor
@Tag(name = "Auth")
public class AuthController {
    private static final String DEVICE_ID_HEADER = "Device-Id";
    private static final String EMAIL_VERIFIED_REDIRECT_PATH = "/#/login?verified=true";
    private final AuthService authService;
    private final EmailChangeService emailChangeService;
    private final FrontendProperties frontendProperties;

    @Operation(
            operationId = "registerUser",
            summary = "Register a user",
            description = "Creates a user account and returns a privacy-safe generic message. "
                    + "A verification email is sent when registration succeeds."
    )
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
            content = @Content(examples = @ExampleObject(value = OpenApiExampleValues.REGISTER_REQUEST_JSON))
    )
    @PostMapping("/register")
    public MessageResponseDto register(@Valid @RequestBody RegisterRequestDto requestDto) {
        authService.register(requestDto);
        return new MessageResponseDto("Registration successful. Please check your email to verify your account.");
    }

    @Operation(
            operationId = "verifyEmail",
            summary = "Verify email address",
            description = "Verifies an email action token and redirects to the configured frontend URL."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "302",
                    description = "Email verified; Location redirects to frontend.",
                    headers = @Header(
                            name = HttpHeaders.LOCATION,
                            description = "Frontend redirect URL.",
                            schema = @Schema(type = "string", format = "uri")
                    ),
                    content = @Content
            ),
            @ApiResponse(responseCode = "400", ref = "#/components/responses/BadRequest"),
            @ApiResponse(responseCode = "429", ref = "#/components/responses/TooManyRequests"),
            @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalServerError")
    })
    @GetMapping("/verify")
    public ResponseEntity<Void> verifyEmail(
            @Parameter(
                    description = "Email verification token. URL-safe token generated by the backend.",
                    example = OpenApiExampleValues.EMAIL_ACTION_TOKEN,
                    schema = @Schema(
                            minLength = 43,
                            maxLength = 43,
                            pattern = "^[A-Za-z0-9_-]{43}$"
                    )
            )
            @RequestParam @ValidEmailActionToken String token
    ) {
        authService.verifyEmail(token);

        return ResponseEntity.status(HttpStatus.FOUND)
                .location(URI.create(frontendProperties.baseUrl().replaceAll("/+$", "")
                                + EMAIL_VERIFIED_REDIRECT_PATH))
                .build();
    }

    @Operation(
            operationId = "verifyEmailChange",
            summary = "Verify email change",
            description = "Confirms a pending email change and returns a privacy-safe generic message."
    )
    @PostMapping("/verify-email-change")
    public MessageResponseDto verifyEmailChange(@Valid @RequestBody VerifyEmailChangeRequestDto requestDto) {
        emailChangeService.verifyEmailChange(requestDto.token());
        return new MessageResponseDto("Email changed successfully.");
    }

    @Operation(
            operationId = "resendVerificationEmail",
            summary = "Resend verification email",
            description = "Returns the same privacy-safe generic response whether or not an unverified account exists."
    )
    @PostMapping("/resend-verification")
    public MessageResponseDto resendVerificationEmail(
            @Valid @RequestBody ResendVerificationEmailRequestDto requestDto
    ) {
        authService.resendVerificationEmail(requestDto.email());
        return new MessageResponseDto(
                "If an unverified account exists, a new verification email has been sent."
        );
    }

    @Operation(
            operationId = "forgotPassword",
            summary = "Request password reset",
            description = "Returns the same privacy-safe generic response whether or not an account exists."
    )
    @PostMapping("/forgot-password")
    public MessageResponseDto forgotPassword(@Valid @RequestBody ForgotPasswordRequestDto requestDto) {
        authService.forgotPassword(requestDto.email());
        return new MessageResponseDto(
                "If an account with this email exists, password reset instructions have been sent."
        );
    }

    @Operation(
            operationId = "resetPassword",
            summary = "Reset password",
            description = "Resets a password using a password reset token."
    )
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
            content = @Content(examples = @ExampleObject(value = OpenApiExampleValues.RESET_PASSWORD_REQUEST_JSON))
    )
    @PostMapping("/reset-password")
    public MessageResponseDto resetPassword(@Valid @RequestBody ResetPasswordRequestDto requestDto) {
        authService.resetPassword(requestDto);
        return new MessageResponseDto("Password has been reset successfully.");
    }

    @Operation(
            operationId = "login",
            summary = "Log in",
            description = "Authenticates by email and password. Device-Id is required and must be a UUID."
    )
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
            content = @Content(examples = @ExampleObject(value = OpenApiExampleValues.LOGIN_REQUEST_JSON))
    )
    @PostMapping("/login")
    public AuthResponseDto login(
            @Valid @RequestBody LoginRequestDto requestDto,
            @Parameter(
                    description = "Required device identifier in UUID format.",
                    example = OpenApiExampleValues.DEVICE_ID,
                    required = true
            )
            @RequestHeader(DEVICE_ID_HEADER) @ValidDeviceId String deviceId
    ) {
        return authService.login(requestDto, deviceId);
    }

    @Operation(
            operationId = "refreshToken",
            summary = "Refresh access token",
            description = "Refreshes tokens for the current device. Device-Id is required and must be a UUID."
    )
    @PostMapping("/refresh")
    public AuthResponseDto refresh(
            @Valid @RequestBody RefreshTokenRequestDto requestDto,
            @Parameter(
                    description = "Required device identifier in UUID format.",
                    example = OpenApiExampleValues.DEVICE_ID,
                    required = true
            )
            @RequestHeader(DEVICE_ID_HEADER) @ValidDeviceId String deviceId
    ) {
        return authService.refresh(requestDto.refreshToken(), deviceId);
    }

    @Operation(
            operationId = "logout",
            summary = "Log out current device",
            description = "Requires an active user: authenticated, email verified, and not banned. "
                    + "Device-Id is required and must be a UUID.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @PostMapping("/logout")
    public MessageResponseDto logout(
            @AuthenticationPrincipal AuthenticatedUserPrincipal principal,
            @Parameter(
                    description = "Required device identifier in UUID format.",
                    example = OpenApiExampleValues.DEVICE_ID,
                    required = true
            )
            @RequestHeader(DEVICE_ID_HEADER) @ValidDeviceId String deviceId
    ) {
        authService.logoutCurrentDevice(principal.getUserId(), deviceId);
        return new MessageResponseDto("Logged out successfully.");
    }
}
